### ISSUE TITLE
mod clash

### ISSUE THREAD

**Issue by mrPassion78** [Frvetz/FS22_SlipDestroysFields#11]
Hi there, i have found a mod that has overwitten youre mod in the settings menu.
with the mod: FS22_LowerReverseBeepVol active, the settings from youre mod are gone.

after removing the mod FS22_LowerReverseBeepVol, youre settings are back.

Not a problem for me, sins youre mod has 100 times higher proirity that that beep mod.. LOL

keep up the good work.. i love this mod.

**Comment by Frvetz** [comment]
Hi mate!

hahah many thanks! I will have a look at it and pass it on to the modder of LowerReverseBeepVol since I know him :)

Thanks for letting me know!!
