### ISSUE TITLE
Integration to REAWheels

### ISSUE THREAD

**Issue by Tubezki** [Frvetz/FS22_SlipDestroysFields#12]
Hi, this mod would be awesome but it wont work with REAWheels mod which is a must for many players. That mod will auctually make your tires slippery in fields but it dont add this ground destruction like your mod does. Is it possible to make it work with REAWheels so basically that REAWheels works but this mod adds the destruction to the fields. Now if you use both this mod will make REAWheels to not work properly and suddenly all tires are very grippy like in basegame...

**Comment by Tubezki** [comment]
Never mind! I see its working now. Since version 1.0.0.0 came out it did not work but now days its fixed! This is nice!

**Comment by Frvetz** [comment]
Alright, nice to hear :) but thanks for reaching out anyways

**Comment by Frvetz** [comment]
If you have any other problems just let me know :)
