### ISSUE TITLE
Issues with FS22_ShowFilltypeName...

### ISSUE THREAD

**Issue by FirenzeIT** [Frvetz/FS22_SlipDestroysFields#13]
Hello, as a subject i have an issues with the mod: FS22_ShowFilltypeName.. With SlipDestroysFields the other mod NOT showing any info about the name of crop, but without this, them works fine. It's possible to fix them please?? I have also a mod called FS22_cropDestructionPlus (and this with ShowFillTypeName only, works fine)..

**Comment by Frvetz** [comment]
Sorry for answering so late! I'll take a look at it

**Comment by Frvetz** [comment]
So I did some testing now and couldn't find any problem with the mod "FS22_ShowFilltypeName" myself.

Maybe you could try a different mod with the same function called "FS22_ShowFillLevelName" from modhub ([link](https://www.farming-simulator.com/mod.php?mod_id=284539)).

Or give me some more information about your game language, vehicle, trailer, fruit, log.txt file etc... 

Thank you :)

Cheers

**Comment by FirenzeIT** [comment]
Hi, since Nov 23 there have been several updates, the FS22_ShowFilltypeName mod I had uninstalled it shortly after and I am using the FS22_ShowFillLevelName without any kind of problem. You can close the thread 👍🏻

**Comment by Frvetz** [comment]
Alright, awesome! 😃
