### ISSUE TITLE
Mod suggestion

### ISSUE THREAD

**Issue by thekalbb** [Frvetz/FS22_SlipDestroysFields#14]
Hi, love the mod.

Looking at your code i see that you have functionallity that i have been looking for. Like knowing where the wheels are touching the ground and placing texture/fieldstate there.

I wanted to find a mod that could put down terrain/paint from the wheel locations of whatever youre driving / or a special impliment, so that you can paint roads while driving like in the picture. (With on/off functionallity)

Maybe you would be interested in making something like that? As a seperate mod.

![mod-request-toll-to-draw-small-fireroads-v0-0atljn4lfcvb1](https://github.com/Frvetz/FS22_SlipDestroysFields/assets/20153559/bfe39b91-51ad-40de-974a-c36094829381)

As you can see in the picture its not very pretty when using the editor - for making long roads.
With a tool like this you could just enable gps hold direction to make straight roads for miles.

You could also expand on it, and put down multiple textures randomly / water puddle paint based on height map etc. like this:

![mod-request-toll-to-draw-small-fireroads-v0-c3vans25gcvb1](https://github.com/Frvetz/FS22_SlipDestroysFields/assets/20153559/70db1767-df88-442f-b83c-e9abbfbc0cf2)

Maybe even add options on the tool to chose what textures should be placed like:
On wheel location; "Dirt" / "Asphalt" / etc
Between wheels: "Grass"

Sorry to ask you to make something unsolicited, but i think Wheel slip mod is the only one i seen that comes close to what i imagined.

Thanks for reading anyway.

Kal.

**Comment by Frvetz** [comment]
Hey Kal,

this is definitely an awesome idea!! But I think I'll have to pass for now. 

I'm currently working on a ModHub release for another script of mine which is already here on GitHub (RealisticDamageSystem) and that's just taking all my time right now (fixing bugs and adding new functions that were suggested).

I am going to write your idea down but I'm not sure if or when I will take a closer look at it. 

But thank you anyway for suggesting it!!

Cheers
Gerrit / frvetz
