### ISSUE TITLE
New setting needed ( I hope you can do it )

### ISSUE THREAD

**Issue by Tubezki** [Frvetz/FS22_SlipDestroysFields#17]
Hello,

I modified your script to allow wheel slip to destroy ground also outside of fields, example when driving on a forest with a forestry machine, I hope you could implement a setting to allow wheel slip to destroy ground outside of field anywhere on map. Just make it that when wheel is on HARD_TERRAIN, example in a gravel road, it won't allow ground to be destroyed, but only on field and soft_terrain anywhere on map.

Also Giants has a bug that some gravel roads are "soft_terrain" so you could avoid it by detecting  that if wheel emits dust in gravel, then its set as "hard_terrain" and when driving on a soft_terrain aka on grass parts of the map, wheels dont emit any dust, so then its "soft_terrain" and this means that forestry machines can also destroy the ground.

I kinda implemented this not fully but for my use now, and I hope you could bring an update to everyone enjoy it, you can just add one more preset or modify the current "allow destroy outside of fields" to make it even better, since now it just barely allow outside of fields the ground to be destryoed.

**Comment by Frvetz** [comment]
Thank you for the idea! Sounds interesting to say the least

Honestly I didn't even know it was possible to change the ground outside of fields... Could you maybe give me some insights on your changes? 

Cheers

**Comment by Tubezki** [comment]
I sent you message in Discord, I can show you what I did, my discord is Tubez47.

Also here is how it looks with realistic physics and settings, I can tell you this looks really really good...
https://youtu.be/85m6S_pTuoE?si=vQJOCYcDmURvnIXs&t=464

**Comment by Tubezki** [comment]
Also here in the beginning of my video you can see amazing actions with my settings: https://youtu.be/85m6S_pTuoE?si=pJBLChKIuMEqhKSx&t=256

**Comment by Frvetz** [comment]
Oh wow yes! Looks like your pretty experienced in scripting :D I'll close this for now and answer you on discord!
